//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication3
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContainerRelations
    {
        public int ContainerID { get; set; }
        public int TaskID { get; set; }
        public int RelationID { get; set; }
    
        public virtual Containers Containers { get; set; }
        public virtual Tasks Tasks { get; set; }
    }
}
