//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication3
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Mediametrie_appEntities : DbContext
    {
        public Mediametrie_appEntities()
            : base("name=Mediametrie_appEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ContainerRelations> ContainerRelations { get; set; }
        public virtual DbSet<Containers> Containers { get; set; }
        public virtual DbSet<Tasks> Tasks { get; set; }
    }
}
